import PDFDocument from 'pdfkit';

export const generateScorecard = (result, exam, user) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50, size: 'A4' });
      const buffers = [];

      doc.on('data', (chunk) => buffers.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(buffers)));

      // Header
      doc.fontSize(28).fillColor('#6366f1').text('TestNova', { align: 'center' });
      doc.fontSize(10).fillColor('#94a3b8').text('AI-Powered Exam Platform', { align: 'center' });
      doc.moveDown(0.5);
      doc.strokeColor('#334155').lineWidth(1).moveTo(50, doc.y).lineTo(545, doc.y).stroke();
      doc.moveDown(1);

      // Student Info
      doc.fontSize(14).fillColor('#f1f5f9').text('SCORE REPORT', { align: 'center' });
      doc.moveDown(0.5);
      doc.fontSize(11).fillColor('#e2e8f0');
      doc.text(`Student: ${user.name}`);
      doc.text(`Email: ${user.email}`);
      doc.text(`Exam: ${exam.title}`);
      doc.text(`Date: ${new Date(result.createdAt).toLocaleDateString()}`);
      doc.moveDown(1);

      // Score summary
      doc.strokeColor('#334155').lineWidth(1).moveTo(50, doc.y).lineTo(545, doc.y).stroke();
      doc.moveDown(0.5);
      doc.fontSize(16).fillColor('#6366f1').text('Score Summary', { underline: true });
      doc.moveDown(0.5);

      doc.fontSize(12).fillColor('#e2e8f0');
      doc.text(`Total Score: ${result.score} / ${result.totalMarks}`);
      doc.text(`Correct: ${result.correctCount}`);
      doc.text(`Wrong: ${result.wrongCount}`);
      doc.text(`Unattempted: ${result.unattempted}`);
      doc.text(`Accuracy: ${result.accuracy.toFixed(1)}%`);
      doc.text(`Percentile (est.): ${result.percentile.toFixed(1)}`);
      doc.moveDown(1);

      // Subject-wise
      if (result.subjectWise && result.subjectWise.length > 0) {
        doc.fontSize(16).fillColor('#6366f1').text('Subject-wise Performance', { underline: true });
        doc.moveDown(0.5);

        const tableTop = doc.y;
        const col1 = 50, col2 = 200, col3 = 280, col4 = 350, col5 = 430;

        doc.fontSize(10).fillColor('#94a3b8');
        doc.text('Subject', col1, tableTop);
        doc.text('Score', col2, tableTop);
        doc.text('Correct', col3, tableTop);
        doc.text('Wrong', col4, tableTop);
        doc.text('Accuracy', col5, tableTop);

        let y = tableTop + 20;
        doc.fillColor('#e2e8f0');
        result.subjectWise.forEach((sw) => {
          doc.text(sw.subject, col1, y);
          doc.text(`${sw.score}/${sw.totalMarks}`, col2, y);
          doc.text(`${sw.correct}`, col3, y);
          doc.text(`${sw.wrong}`, col4, y);
          doc.text(`${sw.accuracy.toFixed(1)}%`, col5, y);
          y += 18;
        });
        doc.y = y;
        doc.moveDown(1);
      }

      // Footer
      doc.fontSize(8).fillColor('#64748b').text(
        'Generated by TestNova AI Platform | This is a computer-generated document.',
        50, 770, { align: 'center', width: 495 }
      );

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
};
